a=list(range(11))
print("la lista resultante al primer enunciado es: ", a)
b=list(range(-10, 1))
print("la lista resultante al segundo enunciado es: ", b)
c=list(range(0, 21, 2))
print("la lista resultante al tercer enunciado es: ", c)
d=list(range(-19, 0, 2))
print("la lista resultante al cuarto enunciado es: ", d)
e=list(range(0, 50, 5))
print("la lista resultante al quinto enunciado es: ", e)